[package]
name = "guzuta"
version = "0.4.1"
authors = ["Kohei Suzuki <eagletmt@gmail.com>"]
description = "Custom repository manager for ArchLinux pacman"
homepage = "https://github.com/eagletmt/guzuta"
repository = "https://github.com/eagletmt/guzuta"
readme = "README.md"
license = "MIT"
edition = "2018"

[dependencies]
anyhow = "1.0"
base64 = "0.13"
bytes = "0.5"
clap = "2.33"
env_logger = "0.8"
flate2 = "1.0"
futures = "0.3"
gpgme = "0.9"
log = "0.4"
rusoto_core = { version = "0.45", default-features = false, features = ["rustls"] }
rusoto_s3 = { version = "0.45", default-features = false, features = ["rustls"] }
rust-crypto = "0.2"
rust-lzma = "0.5"
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.8"
tar = "0.4"
tempdir = "0.3"
tokio = { version = "0.2", features = ["full"] }
zstd = "0.5"
